config/routes.rb
Rails.application.routes.draw do
  namespace :git_connector do
    namespace :admin do
      resources :global_settings
    end

    resources :projects, only: [:show] do
      resources :repos, controller: 'repos'
    end
    patch 'projects/:project_id/repos/:id/toggle_webhook', to: 'repos#toggle_webhook', as: :project_repo_toggle_webhook
    get '/projects/:project_id/connect', to: 'repos#connect', as: :project_repo_connect
    delete '/projects/:project_id/disconnect', to: 'repos#disconnect', as: :project_repo_disconnect
    get 'projects/oauth/callback', to: 'repos#oauth_callback', as: :project_oauth_callback
  end
  post '/webhooks/receive/:provider', to: 'webhooks#receive', as: :webhook_receive
end

app/models/git_connector/global_setting.rb
module GitConnector
  class GlobalSetting < ApplicationRecord
    self.table_name = "git_connector_global_settings"
    enum provider: { github: 0, gitlab: 1, gitbucket: 2 }
    encrypts :client_secret
    validates :provider, presence: true, uniqueness: true
    validates :client_id, :client_secret, presence: true
  end
end

app/controllers/git_connector/admin/global_settings_controller.rb
module GitConnector
  module Admin
    class GlobalSettingsController < ApplicationController
      before_action :require_admin
      before_action :set_provider, only: %i[edit update destroy]

      layout "admin"

      def index
        @providers = GitConnector::GlobalSetting.all
      end

      def new
        @provider = GitConnector::GlobalSetting.new
      end

      def create
        @provider = GitConnector::GlobalSetting.new(provider_params)
        save_and_redirect(@provider, :new, "Provider created successfully")
      end

      def edit; end

      def update
        save_and_redirect(@provider, :edit, "Provider updated successfully")
      end

      def destroy
        if @provider.destroy
          flash[:notice] = "Provider deleted successfully"
        else
          flash[:error] = "Failed to delete provider"
        end
        redirect_to git_connector_admin_global_settings_path
      end

      private

      def set_provider
        @provider = GitConnector::GlobalSetting.find(params[:id])
      end

      def provider_params
        params.require(:git_connector_global_setting)
              .permit(:provider, :client_id, :client_secret, :base_url)
      end

      def save_and_redirect(resource, render_action, success_message)
        if resource.save
          flash[:notice] = success_message
          redirect_to git_connector_admin_global_settings_path
        else
          render render_action
        end
      end
    end
  end
end

app/views/git_connector/admin/global_settings/_form.html.erb
<%= title  ['Global Settings', git_connector_admin_global_settings_path], 
          (@provider.new_record? ? l(:label_new_provider) : l(:label_edit_provider)) %>

<%= error_messages_for(@provider)%>
<%= form_with(model: @provider,
              url: @provider.new_record? ? git_connector_admin_global_settings_path : git_connector_admin_global_setting_path(@provider),
              local: true,
              html: { class: "tabular" }) do |f| %>
  <div class="box">
    <p>
      <%= f.label :provider, l(:field_provider) %>
      <%= f.select :provider,
                   GitConnector::GlobalSetting.providers.keys.map { |p| [p.titleize, p] },
                   { include_blank: l(:label_select_provider) },
                   class: "select" %>
    </p>

    <p>
      <%= f.label :client_id, l(:field_client_id) %>
      <%= f.text_field :client_id, class: "text" %>
    </p>

    <p>
      <%= f.label :client_secret, l(:field_client_secret) %>
      <%= f.password_field :client_secret, class: "text" %>
    </p>

    <p>
      <%= f.label :base_url, l(:field_base_url) %>
      <%= f.text_field :base_url, class: "text" %>
      <em><%= l(:text_optional_base_url) %></em>
    </p>
  </div>
  <%= f.submit l(:button_save), class: "button" %>
<% end %>
<%= javascript_include_tag 'git_connector_admin', plugin: 'redmine_git_connect_pro' %>

app/views/git_connector/admin/global_settings/edit.html.erb
<%= render 'form' %>

app/views/git_connector/admin/global_settings/index.html.erb
<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'git_connector', plugin: 'redmine_git_connect_pro' %>
<% end %>

<div class="contextual">
  <%= link_to "Add New Provider", new_git_connector_admin_global_setting_path, class: "button" %>
</div>
<h2>Global Git Providers</h2>


<table class="list">
  <tr>
    <th>Provider</th>
    <th>Client ID</th>
    <th>Actions</th>
  </tr>
  <% @providers.each do |p| %>
    <tr>
      <td><%= p.provider.titleize %></td>
      <td><%= p.client_id %></td>
      <td>
        <%= link_to "Edit", edit_git_connector_admin_global_setting_path(p), class: 'icon icon-edit' %>
        <%= link_to "Delete", git_connector_admin_global_setting_path(p), method: :delete, data: { confirm: "Are you sure?" } , class: 'icon icon-del' %>
      </td>
    </tr>
  <% end %>
</table>
<%= javascript_include_tag 'git_connector_admin', plugin: 'redmine_git_connect_pro' %>

app/views/git_connector/admin/global_settings/new.html.erb
<%= render 'form' %>