config/routes.rb
Rails.application.routes.draw do
  namespace :git_connector do
    namespace :admin do
      resources :global_settings
    end

    resources :projects, only: [:show] do
      resources :repos, controller: 'repos'
    end
    patch 'projects/:project_id/repos/:id/toggle_webhook', to: 'repos#toggle_webhook', as: :project_repo_toggle_webhook
    get '/projects/:project_id/connect', to: 'repos#connect', as: :project_repo_connect
    delete '/projects/:project_id/disconnect', to: 'repos#disconnect', as: :project_repo_disconnect
    get 'projects/oauth/callback', to: 'repos#oauth_callback', as: :project_oauth_callback
  end
  post '/webhooks/receive/:provider', to: 'webhooks#receive', as: :webhook_receive
end

app/models/git_connector/commit.rb
class GitConnector::Commit < ApplicationRecord
  self.table_name = 'git_connector_commits'
  belongs_to :repo, class_name: "GitConnector::Repo"
  belongs_to :issue, optional: true
end

app/models/git_connector/global_setting.rb
module GitConnector
  class GlobalSetting < ApplicationRecord
    self.table_name = "git_connector_global_settings"
    enum provider: { github: 0, gitlab: 1, gitbucket: 2 }
    encrypts :client_secret
    validates :provider, presence: true, uniqueness: true
    validates :client_id, :client_secret, presence: true
  end
end

app/models/git_connector/pull_request.rb
module GitConnector
  class PullRequest < ApplicationRecord
    self.table_name = 'git_connector_pull_requests'
    belongs_to :repo, class_name: "GitConnector::Repo"
    belongs_to :issue, optional: true
  end
end

app/models/git_connector/repo.rb
module GitConnector
  class Repo < ApplicationRecord
    self.table_name = 'git_connector_repos'
    belongs_to :project

    validates :provider, :repo_name, :repo_url, presence: true

    enum provider: { github: 0, gitlab: 1, gitbucket: 2, other: 3 }

    # Encrypt tokens
    encrypts :access_token
    encrypts :refresh_token
  end
end

app/controllers/git_connector/admin/global_settings_controller.rb
module GitConnector
  module Admin
    class GlobalSettingsController < ApplicationController
      before_action :require_admin
      before_action :set_provider, only: %i[edit update destroy]

      layout "admin"

      def index
        @providers = GitConnector::GlobalSetting.all
      end

      def new
        @provider = GitConnector::GlobalSetting.new
      end

      def create
        @provider = GitConnector::GlobalSetting.new(provider_params)
        save_and_redirect(@provider, :new, "Provider created successfully")
      end

      def edit; end

      def update
        save_and_redirect(@provider, :edit, "Provider updated successfully")
      end

      def destroy
        if @provider.destroy
          flash[:notice] = "Provider deleted successfully"
        else
          flash[:error] = "Failed to delete provider"
        end
        redirect_to git_connector_admin_global_settings_path
      end

      private

      def set_provider
        @provider = GitConnector::GlobalSetting.find(params[:id])
      end

      def provider_params
        params.require(:git_connector_global_setting)
              .permit(:provider, :client_id, :client_secret, :base_url)
      end

      def save_and_redirect(resource, render_action, success_message)
        if resource.save
          flash[:notice] = success_message
          redirect_to git_connector_admin_global_settings_path
        else
          render render_action
        end
      end
    end
  end
end

app/controllers/git_connector/repos_controller.rb
require 'net/http'
require 'uri'
require 'json'

module GitConnector
  class ReposController < ApplicationController
    helper :sort
    include SortHelper

    before_action :find_project, except: [:oauth_callback]
    before_action :authorize, except: [:connect, :oauth_callback, :disconnect]
    before_action :set_repo, only: [:edit, :update, :toggle_webhook, :disconnect, :destroy]

    def index
      sort_init 'repo_name', 'asc'
      sort_update(
        'repo_name'       => "#{Repo.table_name}.repo_name",
        'created_at' => "#{Repo.table_name}.created_at",
        'updated_at' => "#{Repo.table_name}.updated_at"
      )

      scope = @project.git_connector_repos
      scope = apply_filters(scope)
      scope = scope.reorder(sort_clause)

      paginate_repos(scope)
    end

    def new
      @repo = @project.git_connector_repos.build
      load_providers
    end

    def create
      @repo = @project.git_connector_repos.build(repo_params)
      if @repo.save
        flash[:notice] = l(:notice_successful_create)
        redirect_to action: :index
      else
        load_providers
        render :new
      end
    end

    def edit
      load_providers
    end

    def update
      if @repo.update(repo_params)
        flash[:notice] = l(:notice_successful_update)
        redirect_to action: :index
      else
        load_providers
        render :edit
      end
    end

    def toggle_webhook
      service = build_webhook_service(@repo)

      if @repo.webhook_active?
        result = service.deactivate_webhook(@repo.webhook_id)
        @repo.update(webhook_active: false, webhook_id: nil, webhook_secret: nil)
        message_key = result[:success] ? :notice_webhook_deactivated : :notice_webhook_not_deactivated
      else
        result = activate_or_create_webhook(@repo, service)
        message_key = result[:success] ? :notice_webhook_activated : :notice_webhook_not_activated
      end

      flash[result[:success] ? :notice : :error] = l(message_key)
      redirect_to git_connector_project_repos_path(@project)
    end

    def connect
      provider = params[:provider]
      global_setting = GitConnector::GlobalSetting.find_by(provider: provider)
      redirect_to oauth_url(provider, global_setting, repo_id: params[:repo_id])
    end

    def disconnect
      @repo.update(access_token: nil, refresh_token: nil)
      flash[:notice] = l(:notice_successful_disconnect, provider: @repo.provider.titleize)
      redirect_to git_connector_project_repos_path(@project)
    end

    def oauth_callback
      state = JSON.parse(params[:state]) rescue {}
      @project   = Project.find(state['project_id'])
      repo       = @project.git_connector_repos.find(state['repo_id'])
      provider   = state['provider']
      setting    = GitConnector::GlobalSetting.find_by(provider: provider)

      token_data = exchange_code_for_token(provider, setting, params[:code])

      repo.update(
        access_token:  token_data["access_token"],
        refresh_token: token_data["refresh_token"]
      )

      flash[:notice] = "#{provider.titleize} #{l(:notice_successful_connection)}"
      redirect_to git_connector_project_repos_path(@project)
    end

    def destroy
      service = build_webhook_service(@repo)
      service.deactivate_webhook(@repo.webhook_id)
      @repo.destroy
      flash[:notice] = l(:notice_successful_delete)
      redirect_to git_connector_project_repos_path(@project)
    end

    private

    ### Helpers ###

    def find_project
      @project = Project.find(params[:project_id])
    end

    def set_repo
      @repo = @project.git_connector_repos.find(params[:id] || params[:repo_id])
    end

    def load_providers
      @providers = GitConnector::GlobalSetting.all
    end

    def repo_params
      params.require(:git_connector_repo).permit(:repo_name, :repo_url, :provider, :access_token, :refresh_token)
    end

    def apply_filters(scope)
      if params[:search].present?
        q = "%#{params[:search]}%"
        scope = scope.where("repo_name LIKE :q OR repo_url LIKE :q", q: q)
      end

      scope = scope.where(provider: params[:provider].downcase) if params[:provider].present?

      case params[:status]
      when "connected"
        scope = scope.where.not(access_token: [nil, ""])
      when "disconnected"
        scope = scope.where(access_token: [nil, ""])
      end

      scope
    end

    def build_webhook_service(repo)
      WebhookService::Factory.build(
        repo.provider,
        repo_url: repo.repo_url,
        access_token: repo.access_token,
        callback_url: webhook_callback_url(repo.provider)
      )
    end

    def activate_or_create_webhook(repo, service)
      if repo.webhook_id.blank?
        result = service.create_webhook
        if result[:success]
          repo.update(
            webhook_id:     result[:id],
            webhook_secret: result[:secret],
            webhook_active: true
          )
          message = 'successfully created'
        else
          repo.update(webhook_active: false)
          message = 'failed to create'
        end
      else
        result = service.activate_webhook(repo.webhook_id)
        message = result[:success] ? 'successfully activated' : 'failed to activate'
        repo.update(webhook_active: result["active"]) if result.is_a?(Hash)
      end

      {
        success: result[:success],
        message: message
      }
    end

    def oauth_url(provider, setting, repo_id:)
      state = { repo_id: repo_id, project_id: @project.id, provider: provider }.to_json

      case provider
      when "github"
        "https://github.com/login/oauth/authorize?" \
        "client_id=#{setting.client_id}" \
        "&redirect_uri=#{oauth_callback_url}" \
        "&scope=repo,admin:repo_hook" \
        "&state=#{CGI.escape(state)}"
      when "gitlab"
        "https://gitlab.com/oauth/authorize?" \
        "client_id=#{setting.client_id}" \
        "&redirect_uri=#{oauth_callback_url}" \
        "&response_type=code&scope=api"
      end
    end

    def exchange_code_for_token(provider, setting, code)
      case provider
      when "github"
        uri = URI.parse("https://github.com/login/oauth/access_token")
        req = Net::HTTP::Post.new(uri)
        req.set_form_data(
          client_id:     setting.client_id,
          client_secret: setting.client_secret,
          code:          code,
          redirect_uri:  oauth_callback_url
        )
        req['Accept'] = 'application/json'

        res = Net::HTTP.start(uri.hostname, uri.port, use_ssl: true) { |http| http.request(req) }
        JSON.parse(res.body)
      when "gitlab"
        uri = URI.parse("https://gitlab.com/oauth/token")
        res = Net::HTTP.post_form(uri,
          client_id:     setting.client_id,
          client_secret: setting.client_secret,
          code:          code,
          grant_type:    "authorization_code",
          redirect_uri:  oauth_callback_url
        )
        JSON.parse(res.body)
      end
    end

    def oauth_callback_url
      Rails.application.routes.url_helpers.git_connector_project_oauth_callback_url(
        host: request.base_url
      )
    end

    def webhook_callback_url(provider)
      Rails.application.routes.url_helpers.webhook_receive_url(
        provider,
        host: request.base_url
      )
    end

    def paginate_repos(scope)
      @repo_count = scope.count
      @limit      = per_page_option
      @repo_pages = Paginator.new(@repo_count, @limit, params[:page])
      @repos      = scope.offset(@repo_pages.offset).limit(@limit)
    end
  end
end

app/views/git_connector/repos/_form.html.erb
<%= title [l(:label_project_plural), projects_path], 
          [@project.name, project_path(@project)], 
          [l(:label_repo_plural), git_connector_project_repos_path(@project)], 
          (@repo.new_record? ? l(:label_repo_new) : l(:button_edit)) %>

<%= error_messages_for @repo %>

<%= form_with(model: [@project, @repo],
              url: @repo.new_record? ? git_connector_project_repos_path(@project) : git_connector_project_repo_path(@project, @repo),
              local: true,
              class: "tabular") do |f| %>

  <div class="box tabular">
    <p>
      <%= f.label :repo_name, l(:field_name) %>
      <%= f.text_field :repo_name, size: 60 %>
    </p>

    <p>
      <%= f.label :repo_url, l(:field_url) %>
      <%= f.text_field :repo_url, size: 60 %>
    </p>

    <p>
      <%= f.label :provider, l(:field_provider) %>
      <%= f.select :provider,
                   @providers.pluck(:provider, :provider).map { |p| [p.first.titleize, p.second] },
                   include_blank: false %>
    </p>
  </div>
  <%= f.submit(@repo.new_record? ? l(:button_create) : l(:button_save)) %>
<% end %>

app/views/git_connector/repos/edit.html.erb
<%= render 'form', repo: @repo, project: @project, providers: @providers %>
<%= javascript_include_tag 'git_connector', plugin: 'redmine_git_connect_pro' %>

app/views/git_connector/repos/index.html.erb
<% extend SortHelper %>
<div class="contextual">
  <% if User.current.allowed_to?(:create, @project) %>
    <p>
      <%= link_to "Add New Repository", new_git_connector_project_repo_path(@project), class: "button" %>
    </p>
  <% end %>
</div>
<h2>Git Repositories</h2>

<%= form_tag(git_connector_project_repos_path(@project), method: :get, class: "filters") do %>
  <p>
    <label for="name">Search:</label>
    <%= text_field_tag :search, params[:search], size: 20 %>

    <label for="provider">Provider:</label>
    <%= select_tag :provider,
          options_for_select([["All", ""], "GitHub", "GitLab", "Bitbucket"], params[:provider]) %>

    <label for="status">Status:</label>
    <%= select_tag :status,
          options_for_select([["All", ""], ["Connected", "connected"], ["Not Connected", "disconnected"]], params[:status]) %>

    <%= submit_tag "Apply", class: "small" %>
    <%= link_to "Clear", git_connector_project_repos_path(@project), class: "icon icon-reload" %>
  </p>
<% end %>
<table class="list">
  <tr>
    <%= sort_header_tag('repo_name', caption: "Name") %>
    <th>URL</th>
    <th>Provider</th>
    <th>Status</th>
    <th>Webhook</th>
    <%= sort_header_tag('created_at', caption: 'Created At') %>
    <th>Actions</th>
  </tr>
  <% @repos.each do |r| %>
    <tr class="<%= cycle('odd', 'even') %>">
      <td><%= r.repo_name %></td>
      <td><%= r.repo_url %></td>
      <td><%= r.provider %></td>
      <td><%= r.access_token.present? ? "Connected" : "Not Connected" %></td>
      <td>
        <% if User.current.allowed_to?("Enable / Disable Webhook", @project) && r.access_token.present? %>
          <%= link_to r.webhook_active ? 'Disable' : 'Enable', git_connector_project_repo_toggle_webhook_path(@project, r), method: :patch %>
        <% else %>
          <%= r.webhook_active ? 'Enabled' : 'Disabled' %>
        <% end %>
      </td>
      <td><%= format_time(r.created_at)%></td>
      <td>
        <% if User.current.allowed_to?(:edit, @project) %>
          <%= link_to "Edit", edit_git_connector_project_repo_path(@project, r), class: 'icon icon-edit'%>
        <% end %>
        <% if User.current.allowed_to?(:authenticate, @project) %>
          <% if r.access_token.blank? %>
            <%= link_to "Connect", git_connector_project_repo_connect_path(@project, provider: r.provider, repo_id: r.id), class: 'icon icon-connect' %>
          <% else %>
            <%= link_to "Disconnect", git_connector_project_repo_disconnect_path(@project, provider: r.provider, repo_id: r.id), class: 'icon icon-disconnect', method: :delete %>
          <% end %>
        <% end %>
        <% if User.current.allowed_to?(:delete, @project) %>
          <%= link_to "Delete", git_connector_project_repo_path(@project, r), method: :delete, class: 'icon icon-del', data: { confirm: "Are you sure?" }%>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>
<%= pagination_links_full(@repo_pages, @repo_count) %>

<%= javascript_include_tag 'git_connector', plugin: 'redmine_git_connect_pro' %>

app/views/git_connector/repos/new.html.erb
<%= render 'form', repo: @repo, project: @project, providers: @providers %>
<%= javascript_include_tag 'git_connector', plugin: 'redmine_git_connect_pro' %>